#
# Module manifest for module 'PowerShellScaffolding'
#
# Generated by: Lars Panzerbj�rn
#
# Generated on: 20/06/2019
#

@{
	# Script module or binary module file associated with this manifest.
	RootModule = 'AzureDevOpsBoardHelper.psm1'

	# Version number of this module.
	ModuleVersion = '1.0.1'

	# ID used to uniquely identify this module
	GUID = '24bf92e5-7cd8-4153-bd6f-55422c162722'

	# Author of this module
	Author = 'Lars Panzerbj�rn'

	# Company or vendor of this module
	CompanyName = 'Ordo Ursus'

	# Copyright statement for this module
	Copyright = '(c) 2019 Lars Panzerbj�rn. All rights reserved.'

	# Description of the functionality provided by this module
	Description = 'Module that will contain scaffolding for a new module structure. This will include various template files to get started quickly.'

	# Minimum version of the Windows PowerShell engine required by this module
	PowerShellVersion = '5.0'

	# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
	FunctionsToExport = '*'

	# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
	CmdletsToExport = '*'

	# Variables to export from this module
	VariablesToExport = '*'

	# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
	AliasesToExport = '*'

	# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
	PrivateData = @{
		PSData = @{
			# Tags applied to this module. These help with module discovery in online galleries.
			Tags = @("Azure DevOps","REST API")
		} # End of PSData hashtable
	} # End of PrivateData hashtable
}
